[package]
name = "ambrosia"
version = "0.1.0"
edition = "2021"


[dependencies]
rltk = "0.8.1"
serde_json = "1.0.82"
serde = { version = "1.0.138", features = ["derive"] }
include_dir = "0.7.2"
rand = "0.8.5"